Algo_Update
luisafuss/muehle-studienarbeit pull request #166
Opened 2021-06-25 12:52 UTC by JulianRetzbach

kannst ja mal testen, ob es bei dir auch funktioniert

2021-07-07 19:42 UTC, luisafuss requested changes
1.  Bitte in der Datei "comments" markieren, was Du abgearbeitet hastz
2. Execution count zurücksetzen
3. Auskommentierte Print-Funktionen etc. entfernen
4. Kommentar 29 bist Du noch gar nicht angegangen, oder?
5. Also teilweise kann ich immer noch nicht nachvollziehen, was da so passiert. Bei den komplexeren Funktionen alpha_beta und best_move_ab solltest du nochmal die Dokumentation verbessern und ggf. jeden Schritt erklären
6. Es sieht an sich erstmal gut aus.Ich weiß aber auch gerade nicht so richtig, wie ich das testen kann.

2021-07-07 19:42 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "Quelle: (https://stackabuse.com/minimax-and-alpha-beta-pruning-in-python/)\r\n",
Hier sollten noch Autor und Jahreszahl ergänzt werden

2021-07-07 19:42 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "    #move-ordering\r\n",
Bitte in der Doku erklären, wie das move-ordering funktioniert.

2021-07-07 19:42 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "Die Funktion `get_order_value(state, player, depth)` erhält den Spielzustand, einen Spieler und die Suchtiefe, und gibt den Wert für diesen Zustand aus der vorherigen Iteration zurück."
Die Funktion wird in alpha-beta verwendet, aber erst später definiert. Bitte nach oben ziehen

2021-07-07 19:42 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "    val, _, _ = Cache_AB.get((state, player, depth-3), (0, -1, 1))\r\n",
Was passiert hier? Warum -3? Warum (0, -1, 1)? Wert = der von der Heuristik ermittelte Wert?

2021-07-07 19:42 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "    return best_value, best_state"
Das sollte dann ganz weg

2021-07-07 19:42 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "import random\r\n",
Muss das hier importiert werden? Wird ja schon iwo anders importiert. Und die Importe hatten wir sonst auch immer am Anfang einer Datei

2021-07-07 19:42 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "    #in tupel-liste einfügen\\n\",\r\n",
```suggestion
    "    #in tupel-liste einfügen\r\n",
```

2021-07-07 19:42 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "    nextStates = []\r\n",
nextStates -> next_states (bzw. dann anderen Namen überlegen, weil Überschneidung mit Funktionsnamen)
In der Doku erklären, was der unterschied zwischen ns und nextStates ist

2021-07-07 19:42 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "            nextStates = sorted(nextStates,key=itemgetter(1),reverse=True)\r\n",
```suggestion
    "            nextStates = sorted(nextStates, key=itemgetter(1), reverse=True)\r\n",
```

2021-07-07 19:42 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "                nextStates[nextStates.index(s)][1] = value\r\n",
du könntest in der Vorschleife mit folgendem arbeiten:
`for idx_s, s in enumerate(nextStates)`
Dann musst Du hier nicht mit der Index-Funktion arbeiten.

2021-07-07 19:42 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "def alpha_beta_pruning(state, player, depth = 6):\r\n",
Da Alpha-Beta-Pruning jetzt ja schneller sein sollte, kann/muss die Tiefe angepasst werden

2021-07-08 16:08 UTC, JulianRetzbach commented on Muehle_Algo.ipynb
> +    "Quelle: (https://stackabuse.com/minimax-and-alpha-beta-pruning-in-python/)\r\n",
Ist ja eigenltich nur ne Bildquelle auf ner Webseite

2021-07-08 16:09 UTC, JulianRetzbach commented on Muehle_Algo.ipynb
> +    "def alpha_beta_pruning(state, player, depth = 6):\r\n",
dann müssten wir aber auch den Aufruf und die Auswertung ändern

2021-07-08 16:19 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "Quelle: (https://stackabuse.com/minimax-and-alpha-beta-pruning-in-python/)\r\n",
Das war Stroetmanns Kommentar. Schreib einfach dazu : Mina Krivokuća, 2019

2021-07-08 16:20 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "def alpha_beta_pruning(state, player, depth = 6):\r\n",
Die Auswertung müssen wir sowieso ändern. Und es sit doch das Ziel der ganzen Aktion, dass wir tiefer kommen?!

2021-07-11 07:56 UTC, JulianRetzbach commented on Muehle_Algo.ipynb
> +    "def alpha_beta_pruning(state, player, depth = 6):\r\n",
stimmt

2021-07-11 09:18 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "    val, _, _ = Cache_AB.get((state, player, depth-3), (0, -1, 1))\r\n",
So lange nicht klar ist, warum hier -3 steht, werde ich den PR nicht akzeptieren

2021-07-11 09:18 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "    nextStates = []\r\n",
Hier hast Du Dir noch nichts überlegt

2021-07-11 09:37 UTC, luisafuss requested changes
1. Du hast den execution count wieder nicht zurückgesetzt
2. In der Doku zu best_move_ab steht noch was von depth = 5. Mach da einfach alle Parameter aus den Klammern raus, das haben wir sonst auch nicht.
3. Bei der Doku zu best_move_ab hätte ich gerne noch die Antworten zu folgenden Fragen:
- was ist der Unterschied zwischen `ns` und `nextStates` , bestenfalls sollte sich das im Namen der Variablen wiederspiegeln
- Was ist die Variable `distance`
- Warum der negative Wert von value_ab
- nach was wird nextStates sortiert, warum wird überhaupt sortiert

2021-07-11 09:37 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "    #move-ordering\r\n",
Schreibe bitte in der Doku noch einen Satz dazu, wie das Ordering funktioniert.

2021-07-13 13:20 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "    val, _, _ = Cache_AB.get((state, player, depth-3), (0, -1, 1))\r\n",
Hab's jetzt verstanden. Passt so

2021-07-14 06:50 UTC, luisafuss requested changes
Sieht gut aus 👏🏻 Nur ein paar mini-Anmerkungen noch

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "Das Sotieren der Zustände zur Verbesserung der Performance des Algorithmus wird innerhalb der Funktion durch eine Liste realisiert, die nach der Befüllung aus dem Cache sortiert wird."
```suggestion
    "Das Sortieren der Zustände zur Verbesserung der Performance des Algorithmus wird innerhalb der Funktion durch eine Liste realisiert. Darin wird für jeden möglichen Folgezustand auch der Wert gespeichert. Nach der Befüllung wird die Liste nach diesen Werten sortiert, sodass dann der beste Folgezustand an erster Stelle steht."
```

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Algo.ipynb
>      "Die Funktion `alpha_beta(state, player, alpha, beta)` erhält die gleichen Werte wie die Funktion `value_ab()` und gibt den Wert für den übergebenen Zustand zurück. Dabei arbeitet `alpha_beta()`
```suggestion
    "Die Funktion `alpha_beta(state, player, alpha, beta, depth)` erhält die gleichen Werte wie die Funktion `value_ab()` und gibt den Wert für den übergebenen Zustand zurück. Dabei arbeitet `alpha_beta()` nach den im Skript vorgestellten Regeln:\r\n",
```

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "Die Funktion `get_order_value(state, player, depth)` erhält den Spielzustand, einen Spieler und die Suchtiefe, und gibt den Wert für diesen Zustand aus der vorherigen Iteration zurück. Verwendet
```suggestion
    "Die Funktion `get_order_value(state, player, depth)` erhält den Spielzustand, einen Spieler und die Suchtiefe, und gibt den von der Heuristik ermittelten Wert für diesen Zustand aus der vorherigen Iteration zurück. Verwendet wird diese Funktion für das Sortieren der Zustände in der Funktion `alpha_beta(state, player, alpha, beta, depth)`."
```

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "    nextStatesAndValues = []\r\n",
```suggestion
    "    next_states_and_values = []\r\n",
```

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "        nextStatesAndValues = nextStatesAndValues + [[s, 0.0]]\r\n",
```suggestion
    "        next_states_and_values = next_states_and_values + [[s, 0.0]]\r\n",
```

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "            for idx_s, s in enumerate(nextStatesAndValues):\r\n",
```suggestion
    "            for idx_s, s in enumerate(next_states_and_values):\r\n",
```

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "                nextStatesAndValues[idx_s][1] = value\r\n",
```suggestion
    "                next_states_and_values[idx_s][1] = value\r\n",
```

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "            nextStatesAndValues = sorted(nextStatesAndValues, key=itemgetter(1), reverse=True)\r\n",
```suggestion
    "            next_states_and_values = sorted(next_states_and_values , key=itemgetter(1), reverse=True)\r\n",
```

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "    best_value = nextStatesAndValues[0][1]\r\n",
```suggestion
    "    best_value = next_states_and_values[0][1]\r\n",
```

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Algo.ipynb
> +    "    best_state = nextStatesAndValues[0][0]\r\n",
```suggestion
    "    best_state = next_states_and_values[0][0]\r\n",
```

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Conclusion.ipynb
> +   "execution_count": 1,
Execution count zurücksetzen

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Conclusion.ipynb
> +    "* `wdh` ist die Anzahl der Wiederholungen einer Tiefenberechnung die für die Bildunge des Durchschnitts genutzt werden\r\n",
Statt `d` und `wdh` sollte man was ausgeschriebenes Englisches nehmen. 
Mein Vorschlag: `max_depth` und `repetition`

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Conclusion.ipynb
>      "import pandas as pd\r\n",
pandas verwendet standardmäßig matplotlib. Deswegen muss das dann glaube ich auch noch in requirements.txt geschrieben werden

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Conclusion.ipynb
>     "metadata": {}
Der ganze Abschnitt davor kann ja dann weg

2021-07-14 06:50 UTC, luisafuss commented on Muehle_Conclusion.ipynb
> +    "mm_avg      = []\r\n",
```suggestion
```

Das wird ja später eh gesetzt, kann also weg.

2021-07-15 20:18 UTC, JulianRetzbach commented on Muehle_Conclusion.ipynb
> +    "mm_avg      = []\r\n",
Brauch ich später für die Anzeige => wäre sonst nicht definiert oder nicht im Scope

2021-07-15 21:59 UTC, luisafuss approved these changes

2021-07-16 09:03 UTC, merged