refactor play_game()
luisafuss/muehle-studienarbeit pull request #168
Opened 2021-07-14 21:34 UTC by luisafuss

2021-07-15 21:38 UTC, JulianRetzbach commented on Muehle_GUI.ipynb
> +    "print(game)"
kann weg

2021-07-15 21:45 UTC, JulianRetzbach commented on Muehle_GUI.ipynb
> +    "print(game)"
kann weg

2021-07-15 21:45 UTC, JulianRetzbach commented on Muehle_GUI.ipynb
> +    "def minimax_turn(self):\n",
Schön ausgelagert

2021-07-15 21:45 UTC, JulianRetzbach commented on Muehle_GUI.ipynb
> +    "import random"
wie oft importieren wir random eigentlich? Gabs doch bestimmt schon mal.

2021-07-15 21:45 UTC, JulianRetzbach commented on Muehle_GUI.ipynb
> +    "1. **Es müssen noch Steine entfernt werden**  - Aufgrund von Mühlen die zuvor geschlossen wurden, dürfen noch Steine entfernt werden. Der zuvor geklickte Stein wird der Funktion `remove_piece()`
```suggestion
    "1. **Es müssen noch Steine entfernt werden**  - Aufgrund von Mühlen, die zuvor geschlossen wurden, dürfen noch Steine entfernt werden. Der zuvor geklickte Stein wird der Funktion `remove_piece()` übergeben, die ihn vom Spielfeld löscht.\n",
```

2021-07-16 12:40 UTC, luisafuss commented on Muehle_GUI.ipynb
> +    "import random"
Nur Da

2021-07-16 21:42 UTC, JulianRetzbach requested changes
clear_output()

2021-07-16 21:47 UTC, JulianRetzbach approved these changes

2021-07-16 21:48 UTC, merged