Feature 23 stein entfernen bei einer mühle
luisafuss/muehle-studienarbeit pull request #30
Opened 2021-01-05 15:55 UTC by JulianRetzbach

kann nur die schlagbaren Steine zurückgeben und anzeigen. Das Entfernen ist noch nicht möglich.

2021-01-05 16:19 UTC, luisafuss requested changes
Ich habe noch nicht getestet, ob es funktioniert. Aber ich hab schon mal einige Anmerkungen zum Stil und der Benennung und so dran gemacht

2021-01-05 16:19 UTC, luisafuss commented on Muehle_Logic.ipynb
> +    "        enemy_player = 1\n",
Es gibt in Utilities eine Funktion opponent()

2021-01-05 16:19 UTC, luisafuss commented on Muehle_Logic.ipynb
> +    "        enemy_player = 1\n",
Vielleicht wäre es sinnvoll deshalb dann auch enemy in opponent umzubennen, aber das sind halt schon einige Stellen...

2021-01-05 16:19 UTC, luisafuss commented on Muehle_Logic.ipynb
> +    "    _,positions = status.pieces\n",
Wir hatten definiert (siehe Muehle_GUI), dass pieces = remaining, board. Dementsprechend müsstest du statt 'positions' 'board' verwenden

2021-01-05 16:19 UTC, luisafuss commented on Muehle_Logic.ipynb
> +    "            enemy_mill_stones.add((2,i))\n",
Für x würde ich hier ring schreiben und für i cell. So wie du's unten auch gemacht hast. Oder zumindest r und c, falls ring und cell zu lang sind

2021-01-05 16:19 UTC, luisafuss commented on Muehle_Logic.ipynb
> +    "    enemy_stones_list = []\n",
Es gibt eine Funktion (player_pieces) in Utilities, die dir alle Steine von einem Spieler zurück gibt. Die könnte hier hilfreich sein.

2021-01-05 16:35 UTC, JulianRetzbach commented on Muehle_Logic.ipynb
> +    "            enemy_mill_stones.add((2,i))\n",
war teilweise copy paste aus  handle mills. Da ist das noch so. Habs aber geändert

2021-01-05 16:37 UTC, JulianRetzbach commented on Muehle_Logic.ipynb
> +    "    enemy_stones_list = []\n",
die funktionen in ulilities hatte ich vergessen

2021-01-05 16:38 UTC, JulianRetzbach commented on Muehle_Logic.ipynb
> +    "    enemy_stones_list = []\n",
um das zu Nutzen bräuchte ich ja erst alle pieces oder?

2021-01-07 09:10 UTC, luisafuss approved these changes
Konnte es grade noch nicht testen, sieht aber gut aus

2021-01-07 09:10 UTC, merged