Anpassungen GUI
luisafuss/muehle-studienarbeit pull request #53
Opened 2021-01-26 22:04 UTC by luisafuss

closes #48

2021-02-18 01:27 UTC, JulianRetzbach requested changes

2021-02-18 01:27 UTC, JulianRetzbach commented on Muehle_GUI.ipynb
> +    "- board = Liste aus 3 Listen, die angeben, ob, und wenn ja welcher Stein dort sitzt. Dabei symbolisiert jede Liste einen Ring. In jeder Lsite sind neun Werte. Je einer für eine Zelle im Ring. Ei
Typo: "Lsite" => Liste

2021-02-18 01:27 UTC, JulianRetzbach commented on Muehle_GUI.ipynb
> +    "- board = Liste aus 3 Listen, die angeben, ob, und wenn ja welcher Stein dort sitzt. Dabei symbolisiert jede Liste einen Ring. In jeder Lsite sind neun Werte. Je einer für eine Zelle im Ring. Ei
Typo: "eien" => einen

2021-02-18 01:29 UTC, JulianRetzbach commented on Muehle_GUI.ipynb
> +    "- board = Liste aus 3 Listen, die angeben, ob, und wenn ja welcher Stein dort sitzt. Dabei symbolisiert jede Liste einen Ring. In jeder Lsite sind neun Werte. Je einer für eine Zelle im Ring. Ei
Mehr konnte ich nicht finden 👍

2021-02-19 08:09 UTC, luisafuss commented on Muehle_GUI.ipynb
> +    "- board = Liste aus 3 Listen, die angeben, ob, und wenn ja welcher Stein dort sitzt. Dabei symbolisiert jede Liste einen Ring. In jeder Lsite sind neun Werte. Je einer für eine Zelle im Ring. Ei
```suggestion
    "- board = Liste aus 3 Listen, die angeben, ob, und wenn ja welcher Stein dort sitzt. Dabei symbolisiert jede Liste einen Ring. In jeder Liste sind neun Werte. Je einer für eine Zelle im Ring. Eine 0 sagt dabei aus, dass an der entsprechenden Position kein Stein ist. Eine 1 oder 2 stehen für einen Stein des zugehörigen Spielers.\n",
```

2021-02-19 08:11 UTC, luisafuss commented on Muehle_GUI.ipynb
> +    "- board = Liste aus 3 Listen, die angeben, ob, und wenn ja welcher Stein dort sitzt. Dabei symbolisiert jede Liste einen Ring. In jeder Lsite sind neun Werte. Je einer für eine Zelle im Ring. Ei
Korrigiert! (Tipp: Nutze am besten bei sowas das Suggestion-Tool, dann kann man das viel einfacher einarbeiten)
![image](https://user-images.githubusercontent.com/54306427/108476597-7fcf0f00-7292-11eb-9552-8021b24d7524.png)

2021-02-19 22:49 UTC, JulianRetzbach approved these changes

2021-02-19 22:51 UTC, merged