Feature/46 codeanpassung logic
luisafuss/muehle-studienarbeit pull request #71
Opened 2021-03-07 19:38 UTC by JulianRetzbach

Da wir make_move, wenn ich mich recht erinnere, sowieso verändern wollten, habe ich hier erstmal nichts modifiziert.

2021-03-07 20:25 UTC, luisafuss requested changes
closes #46 

Auch noch Merge-Conflicts lösen

2021-03-07 20:25 UTC, luisafuss commented on Muehle_Logic.ipynb
> +    "Die Eingabeparameter der Funktion sind der aktuelle Spielstaus, sowie der aktuelle Spieler in der Form 1 für Spieler eins und 2 für Spieler zwei. Zurückgegeben wird die aktuelle Spielphase des ü
```suggestion
    "Die Eingabeparameter der Funktion sind ein Spielstatus, sowie der ein Spieler in der Form 1 für Spieler eins und 2 für Spieler zwei. Zurückgegeben wird die Spielphase des übergebenen Spielers in dem übergebenen Spiel."
```

2021-03-07 20:25 UTC, luisafuss commented on Muehle_Logic.ipynb
> +    "Hierfür wird der aktuelle Spielstatus, sowie die Position des ausgewählten Steines mit ring und cell übergeben. Zurückgegeben wird eine Liste der möglichen Position, auf die gezogen werden kann.
```suggestion
    "Hierfür wird ein Spielstatus, sowie die Position des ausgewählten Steines mit ring und cell übergeben. Zurückgegeben wird eine Liste der möglichen Position, auf die gezogen werden kann."
```

2021-03-07 20:25 UTC, luisafuss commented on Muehle_Logic.ipynb
> +    "Übergeben wird der Funktion `next_positions()` hierfür der aktuelle Spielstatus, der aktuelle Spieler, und die Position des ausgewählten Steines (ring und cell)."
```suggestion
    "Übergeben wird der Funktion `next_positions()` hierfür ein Spielstatus, ein Spieler, und die Position des ausgewählten Steines (ring und cell)."
```

2021-03-07 20:25 UTC, luisafuss commented on Muehle_Logic.ipynb
> +    "Übergeben wird hierfür der aktuelle Spielzustand und der Spieler, für den überprüft wird."
```suggestion
```
Steht ja schon oben drin

2021-03-07 20:25 UTC, luisafuss commented on Muehle_Logic.ipynb
> -    "    return len(currentPlayerMills) #returns count of new mills for the current player"
Jetzt wird ja nur was zurückgegeben, wenn keine neue Mühle dazu gekommen ist. Entweder das auch nicht zurückgeben und die Beschreibung anpassen, oder auch sonst die Länge ausgeben

2021-03-07 20:29 UTC, luisafuss commented on Muehle_Logic.ipynb
> -    "    return len(currentPlayerMills) #returns count of new mills for the current player"
Deswegen funktioniert das Spiel auch nicht mehr, sobald eine Mühle entsteht

2021-03-07 20:54 UTC, JulianRetzbach commented on Muehle_Logic.ipynb
> -    "    return len(currentPlayerMills) #returns count of new mills for the current player"
da hab ich wohl zu viel gelöscht

2021-03-08 10:32 UTC, luisafuss requested changes

2021-03-08 10:32 UTC, luisafuss commented on Muehle_Logic.ipynb
> +    "Die Eingabeparameter der Funktion sind ein Spielstatus, sowie der ein Spieler in der Form 1 für Spieler eins und 2 für Spieler zwei. Zurückgegeben wird die Spielphase des übergebenen Spielers in
```suggestion
    "Die Eingabeparameter der Funktion sind ein Spielstatus, sowie ein Spieler in der Form 1 für Spieler eins und 2 für Spieler zwei. Zurückgegeben wird die Spielphase des übergebenen Spielers in dem übergebenen Spiel."
```

2021-03-08 10:34 UTC, luisafuss commented
Merge conflicts noch lösen, dann sollte es passen

2021-03-08 11:28 UTC, luisafuss commented
Abgelöst durch #74

2021-03-08 11:28 UTC, closed without merging