Feature/86 alpha beta pruning einbinden
luisafuss/muehle-studienarbeit pull request #93
Opened 2021-03-16 15:38 UTC by luisafuss

closes #86

2021-03-19 00:02 UTC, JulianRetzbach requested changes

2021-03-19 00:02 UTC, JulianRetzbach commented on Muehle_GUI.ipynb
> +    "        self.algo1          = algo1 \n",
warum nicht minimax und ab?

2021-03-19 06:50 UTC, luisafuss commented on Muehle_GUI.ipynb
> +    "        self.algo1          = algo1 \n",
Was meinst du?

2021-03-19 14:39 UTC, luisafuss commented on Muehle_GUI.ipynb
> +    "        self.algo1          = algo1 \n",
Ist ersetzt

2021-03-20 22:00 UTC, JulianRetzbach approved these changes

2021-03-20 22:01 UTC, merged